name: MLOps CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install MLflow & Dependencies
        run: pip install mlflow==2.19.0 pandas scikit-learn

      - name: Run MLProject (Basic)
        run: |
          cd MLProject
          mlflow run . --env-manager=local